name: pixabay_prj
description: "An app that listes out pixabay"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  basic_utils: ^5.5.1
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_intl: ^0.0.1
  flutter_native_splash: null
  flutter_screenutil: ^5.7.0
  flutter_secure_storage: ^7.0.1
  popup_banner: ^1.0.0
  flutter_svg: null
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: 
  google_fonts: ^4.0.4
  http_parser: ^4.0.2
  injectable: ^1.5.3
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  flutter_lazy_loading: ^1.1.3
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  lottie: ^2.6.0
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.1.1
  streaming_shared_preferences: ^2.0.0
  url_launcher: null
  uuid: null
  webview_flutter: ^2.0.14
  responsive_builder: ^0.7.0
  get: ^4.6.5
  
  lazy_loading_list: ^1.0.1
  loading_animation_widget: ^1.2.1

dev_dependencies:
  build_runner: ^2.3.3

  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
